### ISSUE TITLE
Revised Alpaca-52k dataset

### ISSUE THREAD

**Issue by akjindal53244** [lunyiliu/CoachLM#2]
Interesting work and very inspiring! Can you make revised Alpaca-52k dataset available to the community?

**Comment by lunyiliu** [comment]
Hi! Thank you for your interesting in this work. You may have to create your own Revised Alpaca52k dataset using the released training data and code, since the original model and dataset are obtained in an in-domain local system and cannot be released.

**Comment by lunyiliu** [comment]
Anyway we are trying to reproduce this whole procedure in the open-domain network and hopefully will release more assets in the near future including the reproduced CoachLM model and the subsequently revised dataset.
